server:
  port: 8080
spring:
  application:
    name: supermark
# Configuração do Kafka
  kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: supermark-group
        auto-offset-reset: earliest
